### ISSUE TITLE
puerts 升级到2.1.0（因为webgl的库升级了），导致ts-loader有问题。

### ISSUE THREAD

**Issue by Yuki001** [zombieyang/puerts-ts-loader#15]
引擎：团结 1.3.4

ts-loader: 2.0.5
puerts: 2.1.0

使用Sample1 工程，出现：

> Exception: undefined:0: Error: c# exception:undefined:0: ReferenceError: require is not defined
 ReferenceError: require is not defined
      at Object.239 (puerts\ts-loader\main.gen.mjs:184824:1)
      at __webpack_require__ (puerts\ts-loader\main.gen.mjs:184876:41)
      at Object.86 (puerts\ts-loader\main.gen.mjs:3427:11)
      at __webpack_require__ (puerts\ts-loader\main.gen.mjs:184876:41)
      at puerts\ts-loader\main.gen.mjs:185021:12
      at puerts\ts-loader\main.gen.mjs:185109:3,

如果 puerts 是 2.0.5 则正常。

**Comment by Yuki001** [comment]
所以说现在所有的puerts相关的包应该都用2.0.5版本的才对。

**Comment by zombieyang** [comment]
https://github.com/zombieyang/puerts-ts-loader/tree/v3
v3分支现在做了非nodejs环境也可以load ts，可以测试下
